apiVersion: v1
kind: ConfigMap
metadata:
  name: html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Pod Hostname</title>
    </head>
    <body>
        <h1>{{HOSTNAME}}</h1>
    </body>
    </html>

