name: Check status of pods and Slack notification

on:
  workflow_dispatch:

jobs:
  connect:
    runs-on: ubuntu-latest

    steps:
      # Настроим SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Устанавливаем конфигурацию SSH для подключения через Bastion
      - name: Configure SSH
        run: |
          # Создаём директорию для SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Параметры подключения для первого хоста
          BASTION_IP="178.124.206.53"        # Укажите IP вашего Bastion сервера
          BASTION_USER="jump_sa"            # Укажите имя пользователя для Bastion
          BASTION_PORT="32510"              # Порт для Bastion сервера (по умолчанию 22)
          REMOTE_HOST_IP="192.168.208.19"   # Укажите IP первого удалённого хоста
          REMOTE_USER="root"                # Укажите имя пользователя для первого удалённого хоста
          REMOTE_PORT="22"                  # Порт для удалённого хоста (по умолчанию 22)

          # Параметры подключения для второго хоста
          REMOTE_HOST_IP_2="192.168.203.10" # Укажите IP второго удалённого хоста
          REMOTE_USER_2="root"              # Укажите имя пользователя для второго удалённого хоста

          # Создаём конфигурацию для SSH
          echo "Host bastion
          Hostname $BASTION_IP
          User $BASTION_USER
          Port $BASTION_PORT
          IdentityFile ~/.ssh/id_rsa" > ~/.ssh/config

          echo "Host remote-host
          Hostname $REMOTE_HOST_IP
          User $REMOTE_USER
          Port $REMOTE_PORT
          ProxyJump bastion" >> ~/.ssh/config

          echo "Host remote-host-2
          Hostname $REMOTE_HOST_IP_2
          User $REMOTE_USER_2
          Port $REMOTE_PORT
          ProxyJump bastion" >> ~/.ssh/config

      # Добавляем Bastion в known_hosts
      - name: Add bastion to known_hosts
        run: |
          # Добавляем Bastion в known_hosts для предотвращения ошибки "Host key verification failed"
          ssh-keyscan -p 32510 178.124.206.53 >> ~/.ssh/known_hosts

      # Добавляем удалённый хост 1 в known_hosts через Bastion
      - name: Add remote host 1 to known_hosts via bastion
        run: |
          # Добавляем удалённый хост 1 в known_hosts через Bastion сервер
          ssh -o StrictHostKeyChecking=no -p 32510 jump_sa@178.124.206.53 ssh-keyscan -p 22 192.168.208.19 >> ~/.ssh/known_hosts

      # Добавляем удалённый хост 2 в known_hosts через Bastion
      - name: Add remote host 2 to known_hosts via bastion
        run: |
          # Добавляем удалённый хост 2 в known_hosts через Bastion сервер
          ssh -o StrictHostKeyChecking=no -p 32510 jump_sa@178.124.206.53 ssh-keyscan -p 22 192.168.203.10 >> ~/.ssh/known_hosts

      # Выполняем команду на первом удалённом хосте через Bastion
      - name: Run kubectl on remote host 1 and check pod statuses
        run: |
          ssh -o StrictHostKeyChecking=no remote-host 'kubectl get pods -A' > pods_output_1.txt

          echo "=== Полный вывод kubectl для первого хоста ==="
          cat pods_output_1.txt

          echo "=== Поды не в статусе Running на первом хосте ==="
          awk '$4 != "Running" && NR > 1' pods_output_1.txt > not_running_pods_1.txt || true
          cat not_running_pods_1.txt || echo "Все поды на первом хосте в статусе Running"

          # Если файл не пустой — шлём в Slack
          if [ -s not_running_pods_1.txt ]; then
            echo "🚨 Найдены поды не в статусе Running на первом хосте. Отправляем в Slack..."
            TEXT=$(cat not_running_pods_1.txt | sed 's/"/\\"/g' | awk '{printf "%s\\n", $0}')
            curl -X POST -H 'Content-type: application/json' \
              --data "{\"text\":\"*Проблемные поды на первом хосте:*\n\`\`\`${TEXT}\`\`\`\"}" \
              ${{ secrets.SLACK_WEBHOOK }}
          fi

      # Выполняем команду на втором удалённом хосте через Bastion
      - name: Run kubectl on remote host 2 and check pod statuses
        run: |
          ssh -o StrictHostKeyChecking=no remote-host-2 'kubectl get pods -A' > pods_output_2.txt

          echo "=== Полный вывод kubectl для второго хоста ==="
          cat pods_output_2.txt

          echo "=== Поды не в статусе Running на втором хосте ==="
          awk '$4 != "Running" && NR > 1' pods_output_2.txt > not_running_pods_2.txt || true
          cat not_running_pods_2.txt || echo "Все поды на втором хосте в статусе Running"

          # Если файл не пустой — шлём в Slack
          if [ -s not_running_pods_2.txt ]; then
            echo "🚨 Найдены поды не в статусе Running на втором хосте. Отправляем в Slack..."
            TEXT=$(cat not_running_pods_2.txt | sed 's/"/\\"/g' | awk '{printf "%s\\n", $0}')
            curl -X POST -H 'Content-type: application/json' \
              --data "{\"text\":\"*Проблемные поды на втором хосте:*\n\`\`\`${TEXT}\`\`\`\"}" \
              ${{ secrets.SLACK_WEBHOOK }}
          fi

      # Загружаем оба файла как артефакты
      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: script-output
          path: |
            pods_output_1.txt
            not_running_pods_1.txt
            pods_output_2.txt
            not_running_pods_2.txt
