name: Docker Build and Push

on:
  push:
    branches: [master]

env:
  IMAGE_NAME: flask-demo  # Здесь определяем имя образа

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./08.Docker
        push: true
        tags: ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest  # Используем IMAGE_NAME здесь

    - name: Slack Notification (Success)
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "✅ Образ ${IMAGE_NAME} успешно собран и загружен."  # Используем переменную IMAGE_NAME здесь

    - name: Slack Notification (Failure)
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "❌ Ошибка при сборке образа ${IMAGE_NAME}."

