name: Check kubectl version via bastion

on:
  workflow_dispatch:

jobs:
  kubectl-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Write SSH private key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Генерируем config с нестандартным портом и ProxyJump
        echo -e "Host bastion\n  HostName $(jq -r '.bastion.ip' ./.github/config/hosts.json)\n  User $(jq -r '.bastion.user' .github/config/hosts.json)\n  Port $(jq -r '.bastion.port // 22' .github/config/hosts.json)\n  StrictHostKeyChecking no\n" >> ~/.ssh/config

        echo -e "Host target\n  HostName $(jq -r '.target.ip' ./.github/config/hosts.json)\n  User $(jq -r '.target.user' .github/config/hosts.json)\n  ProxyJump bastion\n  StrictHostKeyChecking no\n" >> ~/.ssh/config

    - name: Run kubectl via bastion and target
      run: |
        ssh target 'kubectl version --short' | tee kubectl_output.txt

    - name: Upload kubectl version output
      uses: actions/upload-artifact@v4
      with:
        name: kubectl-version
        path: kubectl_output.txt

