name: Setup Minikube Cluster

on:
  pull_request:
    branches:
      - master

jobs:
  minikube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@v0.0.19
        with:
          minikube-version: 'v1.33.1'
          kubernetes-version: 'v1.29.1'
          driver: docker

      - name: Verify cluster status
        run: |
          minikube status
          kubectl version --client
          kubectl cluster-info

      - name: Wait for node to become ready
        run: |
          for i in {1..30}; do
            STATUS=$(kubectl get nodes -o jsonpath='{.items[0].status.conditions[?(@.type=="Ready")].status}')
            if [ "$STATUS" == "True" ]; then
              echo "Node is Ready"
              break
            fi
            echo "Waiting for node to be ready..."
            sleep 5
          done

      - name: Get cluster nodes
        run: |
          kubectl get nodes

