name: Manual Minikube Setup

on:
  pull_request:
    branches:
      - '**'

jobs:
  minikube:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y conntrack curl

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/re

